# URL -> https://github.com/crate-ci/typos

[default.extend-identifiers]

[default.extend-words]
commitlint = "commitlint"
conventionalcommits = "conventionalcommits"
[files]
extend-exclude = [
    "**/.vscode/**/",
    "**/*.json",
    "_typos.toml",
    "cspell.config.yaml",
]
