name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
    
  spell-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - uses: actions/checkout@v3
      - name: Check spelling
        uses: crate-ci/typos@master
        with: 
          config: ./config/_typos.toml
  
  commit-lint-check:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    needs: [spell-check]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v2
        with:
          check-latest-tag-only: true
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'
