
name: Github-Release
on:
  push:
    # Pattern matched against refs/tags
    tags:     
      - '**'
jobs:
  generate-changelog-body:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a dev changelog
        if: |
          contains(github.ref_name, 'dev')
          || contains(github.ref_name, 'development')
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: ./config/cliff-dev.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Generate a changelog
        if: |
          contains(github.ref_name, 'main')
          || contains(github.ref_name, 'master')
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: ./config/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md

      # use release body in the same job
      - name: Upload the binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: binary_release.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}

  # use release body in another job
  upload:
    name: Upload the release
    needs: [generate-changelog-body]
    runs-on: ubuntu-latest
    steps:
      - name: Upload the binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: binary_release.zip
          repo_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
